package utils;

import Exceptions.ToolsException;
import Exceptions.UtilsException;

public class MultiString 
{
	private String[] array = null;
	private int length;
	
	public MultiString(String str, int n, String begin, String end)
	{
		length = str.length() + ( n - 1 ) * 2;
		array = new String[length];
		for (int i = 0; i < n - 1 ; i++) 
		{
			array[i] = begin;
			array[length - i - 1] = end;
		}
		for (int i = 0 ; i < str.length(); i++)
		{
			array[i + n - 1] = str.substring(i, i + 1);
		}
	}
	
	/**
	 * Return the substring generated by appending the Strings in indices begin to end - 1
	 * @param begin
	 * @param end
	 * @return
	 * @throws ToolsException 
	 */
	public String substring(int begin, int end)
	{
		if (begin >= end)
		{
			throw new UtilsException("begin index is higher than end index");
		}
		StringBuilder str = new StringBuilder();
		for (int i = begin; i < end; i++)
		{
			str.append(array[i]);
		}
		return str.toString();
	}
	
	/**
	 * Return the substring generated by appending the Strings in indices begin to the end
	 * @param begin
	 * @return
	 * @throws UtilsException 
	 */
	public String substring(int begin)
	{
		return substring(begin, length);
	}
	
	
	public String get(int i)
	{
		return array[i];
	}
	
	public void set(int i, String str)
	{
		array[i] = str;
	}
	
	public void clear()
	{
		array = null;
	}
	
	public String toString()
	{
		return substring(0);
	}
	
	public int length()
	{
		return length;
	}
}
